config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :workouts do 
    resources :exercises
  end
  root 'workouts#index'
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :workout
  has_one :user, through: :engine
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :workouts
         has_many :exercises, through: :workouts
end

app/models/workout.rb
class Workout < ActiveRecord::Base
    has_many :exercises
     has_attached_file :image,
 :styles => { :medium => "300x300>", :thumb => "100x100#" }
     validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
     
     belongs_to :user
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
    def create 
        @workout = Workout.find(params[:workout_id]) 
        @exercise = @workout.exercises.create(params[:exercise].permit(:name, :sets, :reps))
        
        redirect_to workout_path(@workout)
    end
    
    def edit 
         
    end
    
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    
    before_action :find_workout, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    
    def index 
        @workouts = Workout.all
    end
    
    def show 
       
    end
    
    def new
       # @workout = current_user.workouts.build
       @workout = Workout.new
       @workout.user_id = current_user.id
    end
    
    def create 
        @workout = current_user.workouts.build(workout_params)
        if @workout.save
            redirect_to @workout
            
        else
            render 'new'
        end
    end
    
    def edit 
       
    end
    
     def update 
        
            if @workout.update(workout_params)
                redirect_to @workout
            else
                render 'edit'
            end
     end
     
     def destroy 
         @workout.destroy
         redirect_to root_path
     end
     
     private
     def workout_params 
     params.require(:workout).permit(:date, :workout, :comments, :length, :image)
         
     end
     
     def find_workout 
            @workout = Workout.find(params[:id])
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercise.html.erb
<h3><%= exercise.name %></h3>
<p><%= exercise.sets %> sets of <%= exercise.reps %> reps</p>
<%= link_to "Edit", edit_workout_exercise_path(@workout, @workout.exercises) %>

app/views/exercises/_form.html.erb
            <%= simple_form_for([@workout, @workout.exercises.build]) do |f| %>
            
                <%= f.input :name, input_html: { class: "form-control" } %>
                <%= f.input :sets, input_html: { class: "form-control" } %>
                <%= f.input :reps, input_html: { class: "form-control" } %>
                <br>
                <%= f.button :submit %>
                <% end %>
            

app/views/exercises/edit.html.erb
<h1 class="text-center">Edit Workout</h1>
<%= render partial: "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workout Log</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <a class="navbar-brand">#SHREDDED</a>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Add New Workout", new_workout_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %> </li>
          <% end %>
      </ul>
    </div>
  </nav>
   <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/workouts/_form.html.erb
<div class="container text-center">
    <div class="row">
        <div class= "col-xs-4 col-xs-offset-4">
    <%= simple_form_for(@workout, html: { multipart: true, class: "form-horizontal" }) do |f| %>
        <div class="field">
            <%= f.input :date, label: "Date" %>
        </div>
        <div class="field">
            <%= f.input :workout, label: "What body part(s) did you train?", input_html: { class: "form-control" } %>
        </div>
        <div class="field">
            <%= f.input :comments, label: "Comments", input_html: { class: "form-control" } %>
        </div>
        <div class="field">
        <%= f.input :length, label: "Workout Length", input_html: { class: "form-control" } %>
        </div>
        <br>
        <div class="field">
        <%= f.file_field :image, label: "Selfie", input_html: { class: "form-control" } %>
        </div>
        <%= f.button :submit %><br>
    <% end %>

app/views/workouts/edit.html.erb
<h1 class="text-center">Edit Workout</h1>
<%= render partial: "form" %>

<%= link_to "Delete Workout",  workout_path(@workout), class: "btn btn-danger text-center delete-button",  method: :delete, data:  {confirm: "Are you sure you want to delete?" } %><br>
      </div>
    </div>
</div>

app/views/workouts/index.html.erb
<div class="container text-center">
    <h1>My Workouts</h1>
    
    <%= div_for @workouts, class: "container" %>
    
    <% @workouts.each do |w| %>
    
    <h2><%= w.workout %></h2>
    
    <p><strong>Date:</strong> <%= w.date.strftime("%m/%d/%Y") %></p>
    
    <p><strong>Comments:</strong> <%= w.comments %></p>
    
    <p><strong>Duration:</strong> <%=w.length %></p>
    <%= link_to "View Workout", workout_path(w), class: "btn btn-primary" %>
    <% end %>
    </div>
</div>

app/views/workouts/new.html.erb
<h1 class="text-center">New Workout</h1>

<%= render partial: "form" %>

<%= link_to "Cancel", root_path %>

app/views/workouts/show.html.erb
<div class="container text-center">
    <div class="row">
        <div class= "col-xs-4 col-xs-offset-4">     
            <div class="workout">
                <%= image_tag @workout.image.url(:thumb, timestamp:false) %>
                <p> <strong>Date:</strong> <%= @workout.date.strftime("%m/%d/%Y")  %></p>
                <p> <strong>Body Part(s)</strong>: <%= @workout.workout %></p>
                <p> <strong>Duration:</strong> <%= @workout.length %></p>
                <p> <strong>Comments:</strong> <%= @workout.comments %></p><br>
             
            
            <div id="exercises text-center">
                <h2>Exercises</h2>
                <%= render @workout.exercises %>
                
                <h3>Add an Exercise</h3>
                <%= render "exercises/form" %>
            </div>
            
                
                <%= link_to "Edit", edit_workout_path %><br>
                <%= link_to "Back", root_path %>
                    </div>
                </div>
            </div>
                     
    
</div>